CREATE TABLESPACE UN_DATA
DATAFILE 'C:\app\JeffreyLeiva\oradata\demo\undata.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;

CREATE TABLESPACE UN_Ind
DATAFILE 'C:\app\JeffreyLeiva\oradata\demo\unInd.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;

