CREATE USER un
IDENTIFIED BY un
DEFAULT TABLESPACE un_data
QUOTA 10M ON un_data 
TEMPORARY TABLESPACE temp
QUOTA 5M ON system ;

-- ROLES
GRANT "CONNECT" TO "UN" ;

-- SYSTEM PRIVILEGES
GRANT ALTER ANY INDEX TO "UN" ;
GRANT DROP ANY SEQUENCE TO "UN" ;
GRANT ALTER ANY PROCEDURE TO "UN" ;
GRANT CREATE ANY PROCEDURE TO "UN" ;
GRANT CREATE ANY INDEX TO "UN" ;
GRANT CREATE INDEXTYPE TO "UN" ;
GRANT CREATE ANY SEQUENCE TO "UN" ;
GRANT CREATE VIEW TO "UN" ;
GRANT ALTER ANY TABLE TO "UN" ;
GRANT CREATE SESSION TO "UN" ;
GRANT SELECT ANY TABLE TO "UN" ;
GRANT DELETE ANY TABLE TO "UN" ;
GRANT ALTER ANY SEQUENCE TO "UN" ;
GRANT CREATE TABLE TO "UN" ;
GRANT DROP ANY TABLE TO "UN" ;
GRANT SELECT ANY SEQUENCE TO "UN" ;
GRANT CREATE TABLESPACE TO "UN" ;
GRANT DROP ANY TYPE TO "UN" ;
GRANT EXECUTE ANY PROCEDURE TO "UN" ;
GRANT EXECUTE ANY PROGRAM TO "UN" ;
GRANT CREATE ANY INDEXTYPE TO "UN" ;
GRANT DROP ANY INDEX TO "UN" ;
GRANT ALTER ANY INDEXTYPE TO "UN" ;
GRANT UPDATE ANY TABLE TO "UN" ;
GRANT DROP ANY VIEW TO "UN" ;
GRANT ALTER TABLESPACE TO "UN" ;
GRANT CREATE ANY VIEW TO "UN" ;
GRANT INSERT ANY TABLE TO "UN" ;
GRANT ALTER ANY TYPE TO "UN" ;
GRANT DROP ANY PROCEDURE TO "UN" ;
GRANT DROP ANY INDEXTYPE TO "UN" ;
GRANT UNLIMITED TABLESPACE TO "UN" ;
GRANT CREATE ANY TABLE TO "UN" ;
GRANT CREATE PROCEDURE TO "UN" ;

