ALTER TABLE college
ADD CONSTRAINT pk_college PRIMARY KEY (id_college)
USING INDEX
TABLESPACE un_ind PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0)

ALTER TABLE campus
ADD CONSTRAINT pk_campus PRIMARY KEY (id_campus)
USING INDEX
TABLESPACE un_ind PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0)

ALTER TABLE career
ADD CONSTRAINT pk_career PRIMARY KEY (id_career)
USING INDEX
TABLESPACE un_ind PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0)

ALTER TABLE student
ADD CONSTRAINT pk_student PRIMARY KEY (id_student)
USING INDEX
TABLESPACE un_ind PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0)

ALTER TABLE email
ADD CONSTRAINT pk_email PRIMARY KEY (id_email)
USING INDEX
TABLESPACE un_ind PCTFREE 20
STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 0)

ALTER TABLE campus
ADD CONSTRAINT fk_campus FOREIGN KEY (id_college) references college(id_college)

ALTER TABLE career
ADD CONSTRAINT fk_career FOREIGN KEY (id_campus) references campus(id_campus)

ALTER TABLE student
ADD CONSTRAINT fk_student FOREIGN KEY (id_career) references career(id_career)

ALTER TABLE email
ADD CONSTRAINT fk_email FOREIGN KEY (id_student) references student(id_student)


